- name: Update APT Packages
  apt:
    upgrade: dist
  become: yes

- name: Install APT Dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python-setuptools
    - python3-openimageio
    - python3-venv
    - software-properties-common
    - unzip
  become: yes

- name: Add "ppa:deadsnakes/ppa" APT Repository
  become: yes
  become_method: sudo
  apt_repository:
    validate_certs: no
    repo: 'ppa:deadsnakes/ppa'
    state: present

- name: Install APT Dependencies for Python 3.10
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python3.10
    - python3.10-distutils
  become: yes