- name: Update APT Packages
  apt:
    upgrade: dist
  become: yes

- name: Install APT Dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - graphviz
      - python3-openimageio
      - python3-venv
      - vim
  become: yes
