- name: Check if "Poetry" is Installed
  stat:
    path: "{{ ansible_env.HOME }}/.local/bin/poetry"
  register: poetry_executable

- name: Add "Poem" Function
  blockinfile:
    state: present
    insertafter: EOF
    dest: "{{ ansible_env.HOME }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Add \"Poem\" Function"
    content: |
      # Activate Poetry virtual environment.
      function poem() {
          if [[ -n "$@" ]]; then
              poetry env use "$@"
          else
              poetry env use 3
          fi;

          if [ -f "pyproject.toml" ]; then
              source $(poetry env info -p)/bin/activate
          else
              echo "The current directory has no associated \"poetry\" capability!"
          fi;
      }

- name: Download "Poetry"
  get_url:
    url: https://install.python-poetry.org
    dest: /tmp/install-poetry.py
  when: not poetry_executable.stat.exists

- name: Install "Poetry"
  script: /tmp/install-poetry.py
  args:
    executable: python3
  when: not poetry_executable.stat.exists

- name: Add "Poetry" to "$PATH" in ".bashrc"
  blockinfile:
    state: present
    insertafter: EOF
    dest: "{{ ansible_env.HOME }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Add Poetry to $PATH"
    content: |
      export PATH={{ ansible_env.HOME }}/.local/bin:$PATH

