- name: Update APT Packages
  apt:
    upgrade: dist
  become: yes

- name: Install APT Dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python-setuptools
    - python3-openimageio
    - python3-venv
    - unzip
  become: yes
