- name: Update "apt" Packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
  become: yes

- name: Install "apt" Dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - build-essential
      - git
      - graphviz
      - graphviz-dev
      - python3-dev
      - python3-openimageio
      - python3-venv
      - vim
  become: yes
