- name: Check if "OpenImageIO" Library is Installed
  stat:
    path: /usr/bin/libOpenImageIO.so
  register: openimageio_library

- name: Download "OpenImageIO"
  get_url:
    url: https://github.com/colour-science/artifacts/releases/download/OpenImageIO-Release-2.1.10.1/OpenImageIO-Release-2.1.10.1.zip
    dest: /tmp/OpenImageIO-Release-2.1.10.1.zip
  when: not openimageio_library.stat.exists

- name: Install "OpenImageIO"
  shell: |
    unzip OpenImageIO-Release-2.1.10.1.zip -d OpenImageIO-Release-2.1.10.1
    cp OpenImageIO-Release-2.1.10.1/linux64/bin/* /usr/bin/
    cp -r OpenImageIO-Release-2.1.10.1/linux64/lib/* /usr/lib/
  args:
    chdir: /tmp
  become: yes
  when: not openimageio_library.stat.exists
